
import SpotifyUpcAlbumSearch.AlbumUpc;
import SpotifyUpcAlbumSearch.SystemClipboard;
import com.google.gson.JsonObject;
import com.mycompany.spotifymaven.SpotifyApi;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author equilibrium
 */
public class APIfy extends javax.swing.JFrame {

    private JsonObject jsonObject;

    /**
     * Creates new form NewJFrame
     */
    public APIfy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        albumID = new javax.swing.JTextField();
        albumIdLabel = new javax.swing.JLabel();
        albumNameTextField = new javax.swing.JTextField();
        albumNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coverImageLabel = new javax.swing.JLabel();
        popularityTextField = new javax.swing.JTextField();
        popularityLabel = new javax.swing.JLabel();
        relDateLabel = new javax.swing.JLabel();
        relDateTextField = new javax.swing.JTextField();
        labelLabel = new javax.swing.JLabel();
        labelTextField = new javax.swing.JTextField();
        linkLabel = new javax.swing.JLabel();
        linkTextField = new javax.swing.JTextField();
        artistsLabel = new javax.swing.JLabel();
        artistsTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        CopyMenu = new javax.swing.JMenuItem();
        PasteMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("UPC");

        SearchButton.setText("SEARCH");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        albumID.setBackground(new java.awt.Color(234, 237, 243));
        albumID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                albumIDFocusGained(evt);
            }
        });
        albumID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumIDMouseClicked(evt);
            }
        });
        albumID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumIDActionPerformed(evt);
            }
        });

        albumIdLabel.setText("ID");

        albumNameTextField.setEditable(false);
        albumNameTextField.setBackground(new java.awt.Color(234, 237, 243));
        albumNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumNameTextFieldActionPerformed(evt);
            }
        });

        albumNameLabel.setText("Name");

        jLabel2.setBackground(new java.awt.Color(234, 237, 243));
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        coverImageLabel.setText("Cover");

        popularityTextField.setEditable(false);
        popularityTextField.setBackground(new java.awt.Color(234, 237, 243));
        popularityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popularityTextFieldActionPerformed(evt);
            }
        });

        popularityLabel.setText("Popularity");

        relDateLabel.setText("Release Date");

        relDateTextField.setEditable(false);
        relDateTextField.setBackground(new java.awt.Color(234, 237, 243));
        relDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relDateTextFieldActionPerformed(evt);
            }
        });

        labelLabel.setText("Label");

        labelTextField.setEditable(false);
        labelTextField.setBackground(new java.awt.Color(234, 237, 243));
        labelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelTextFieldActionPerformed(evt);
            }
        });

        linkLabel.setText("Link");

        linkTextField.setEditable(false);
        linkTextField.setBackground(new java.awt.Color(234, 237, 243));
        linkTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkTextFieldMouseClicked(evt);
            }
        });
        linkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkTextFieldActionPerformed(evt);
            }
        });

        artistsLabel.setText("Artists");

        artistsTextField.setEditable(false);
        artistsTextField.setBackground(new java.awt.Color(234, 237, 243));
        artistsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistsTextFieldActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        CopyMenu.setText("Copy");
        CopyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyMenuActionPerformed(evt);
            }
        });
        jMenu2.add(CopyMenu);

        PasteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.META_MASK));
        PasteMenu.setText("Paste");
        PasteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteMenuActionPerformed(evt);
            }
        });
        jMenu2.add(PasteMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(artistsLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(linkLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(albumNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(albumIdLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(popularityLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(labelLabel)))
                                .addGap(14, 14, 14))
                            .addComponent(relDateLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(artistsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(popularityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(albumID, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(albumNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(relDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(coverImageLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchButton)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistsLabel)
                    .addComponent(artistsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumNameLabel)
                    .addComponent(albumNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumIdLabel)
                    .addComponent(albumID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popularityLabel)
                    .addComponent(popularityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relDateLabel)
                    .addComponent(relDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLabel)
                    .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(coverImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PasteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteMenuActionPerformed
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Clipboard clipboard = toolkit.getSystemClipboard();
        String result;
        try {
            result = (String) clipboard.getData(DataFlavor.stringFlavor);
            jTextField1.setText(result);
        } catch (UnsupportedFlavorException | IOException ex) {
            Logger.getLogger(APIfy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PasteMenuActionPerformed

    private void CopyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyMenuActionPerformed
        
        Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
        String s = jTextField1.getSelectedText();
        StringSelection clipString = new StringSelection(s);
        clip.setContents(clipString, null);
        
     
       
       
    }//GEN-LAST:event_CopyMenuActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Empty UPC field");
            return;
        }

        String link = "https://api.spotify.com/v1/search?q=upc:" + jTextField1.getText() + "&type=album";

        System.out.println("The link is: " + link);

        AlbumUpc album = new AlbumUpc(link);

        this.jsonObject = album.getJson(link);

        //albumID.setText(jsonObject.get("id").toString());
        System.out.println(this.jsonObject.toString());

        albumID.setText(album.getAlbumId());

        albumNameTextField.setText(album.getAlbumName());
        
        System.out.println("LINK: ");
        //album.showCoverLink();
        
        
        //https://stackoverflow.com/questions/42752611/display-url-image-into-a-jpanel
        Image coverImage = null;
        URL url = null;
        try {
            url = new URL(album.showCoverLink());
        } catch (MalformedURLException ex) {
            Logger.getLogger(APIfy.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            coverImage = ImageIO.read(url);
        } catch (IOException ex) {
            Logger.getLogger(APIfy.class.getName()).log(Level.SEVERE, null, ex);
        }
        //https://stackoverflow.com/questions/6714045/how-to-resize-jlabel-imageicon
        ImageIcon imageIcon = new ImageIcon(coverImage); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  // transform it back

        jLabel2.setIcon(imageIcon);
        
        //8033772864862
        linkTextField.setText("https://play.spotify.com/album/" + albumID.getText());
        link = "https://api.spotify.com/v1/albums/" + albumID.getText();
        AlbumUpc albumApiId = new AlbumUpc(link);
        this.jsonObject = albumApiId.getJson(link);
        System.out.println("2222");
        System.out.println("2222");
        System.out.println("2222");
        System.out.println("NEW JSON OBJECT: " + this.jsonObject.toString());
        
        labelTextField.setText(albumApiId.getLabelApiId());
        
        relDateTextField.setText(albumApiId.getReleaseDateApiId());
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void albumIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumIDActionPerformed

    private void albumNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumNameTextFieldActionPerformed

    private void popularityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popularityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popularityTextFieldActionPerformed

    private void relDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relDateTextFieldActionPerformed

    private void labelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTextFieldActionPerformed

    private void linkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkTextFieldActionPerformed

    private void artistsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistsTextFieldActionPerformed

    private void albumIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_albumIDFocusGained
        //8033772864862
        
    }//GEN-LAST:event_albumIDFocusGained

    private void albumIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumIDMouseClicked
        SystemClipboard clip = new SystemClipboard();
        clip.copy(albumID.getText());
       
    }//GEN-LAST:event_albumIDMouseClicked

    private void linkTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkTextFieldMouseClicked
        SystemClipboard clip = new SystemClipboard();
        clip.copy(linkTextField.getText());
       
    }//GEN-LAST:event_linkTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APIfy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APIfy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APIfy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APIfy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APIfy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CopyMenu;
    private javax.swing.JMenuItem PasteMenu;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField albumID;
    private javax.swing.JLabel albumIdLabel;
    private javax.swing.JLabel albumNameLabel;
    private javax.swing.JTextField albumNameTextField;
    private javax.swing.JLabel artistsLabel;
    private javax.swing.JTextField artistsTextField;
    private javax.swing.JLabel coverImageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelLabel;
    private javax.swing.JTextField labelTextField;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JTextField linkTextField;
    private javax.swing.JLabel popularityLabel;
    private javax.swing.JTextField popularityTextField;
    private javax.swing.JLabel relDateLabel;
    private javax.swing.JTextField relDateTextField;
    // End of variables declaration//GEN-END:variables
}
