package apiPackage;


import SpotifyUpcAlbumSearch.AlbumUpc;
import SpotifyUpcAlbumSearch.SystemClipboard;
import com.google.gson.JsonObject;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alberto
 */
public class APIfy extends javax.swing.JFrame {
    //variable for debugging purpose
    private JsonObject jsonObject;
    private SystemClipboard clip;

    /**
     * Creates new form NewJFrame
     */
    public APIfy() {
        initComponents();
        this.clip = new SystemClipboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpcTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        albumID = new javax.swing.JTextField();
        albumIdLabel = new javax.swing.JLabel();
        albumNameTextField = new javax.swing.JTextField();
        albumNameLabel = new javax.swing.JLabel();
        coverLabel = new javax.swing.JLabel();
        coverImageLabel = new javax.swing.JLabel();
        popularityTextField = new javax.swing.JTextField();
        popularityLabel = new javax.swing.JLabel();
        relDateLabel = new javax.swing.JLabel();
        relDateTextField = new javax.swing.JTextField();
        labelLabel = new javax.swing.JLabel();
        labelTextField = new javax.swing.JTextField();
        linkLabel = new javax.swing.JLabel();
        linkTextField = new javax.swing.JTextField();
        artistsLabel = new javax.swing.JLabel();
        artistsTextField = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        infoMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CopyMenu = new javax.swing.JMenuItem();
        PasteMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        UpcTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpcTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("UPC");

        SearchButton.setText("SEARCH");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        albumID.setBackground(new java.awt.Color(234, 237, 243));
        albumID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                albumIDFocusGained(evt);
            }
        });
        albumID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumIDMouseClicked(evt);
            }
        });
        albumID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumIDActionPerformed(evt);
            }
        });

        albumIdLabel.setText("ID");

        albumNameTextField.setEditable(false);
        albumNameTextField.setBackground(new java.awt.Color(234, 237, 243));
        albumNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumNameTextFieldMouseClicked(evt);
            }
        });
        albumNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumNameTextFieldActionPerformed(evt);
            }
        });

        albumNameLabel.setText("Name");

        coverLabel.setBackground(new java.awt.Color(234, 237, 243));
        coverLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        coverImageLabel.setText("Cover");

        popularityTextField.setEditable(false);
        popularityTextField.setBackground(new java.awt.Color(234, 237, 243));
        popularityTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popularityTextFieldMouseClicked(evt);
            }
        });
        popularityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popularityTextFieldActionPerformed(evt);
            }
        });

        popularityLabel.setText("Popularity");

        relDateLabel.setText("Release Date");

        relDateTextField.setEditable(false);
        relDateTextField.setBackground(new java.awt.Color(234, 237, 243));
        relDateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relDateTextFieldMouseClicked(evt);
            }
        });
        relDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relDateTextFieldActionPerformed(evt);
            }
        });

        labelLabel.setText("Label");

        labelTextField.setEditable(false);
        labelTextField.setBackground(new java.awt.Color(234, 237, 243));
        labelTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTextFieldMouseClicked(evt);
            }
        });
        labelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelTextFieldActionPerformed(evt);
            }
        });

        linkLabel.setText("Link");

        linkTextField.setEditable(false);
        linkTextField.setBackground(new java.awt.Color(234, 237, 243));
        linkTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkTextFieldMouseClicked(evt);
            }
        });
        linkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkTextFieldActionPerformed(evt);
            }
        });

        artistsLabel.setText("Artists");

        artistsTextField.setEditable(false);
        artistsTextField.setBackground(new java.awt.Color(234, 237, 243));
        artistsTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                artistsTextFieldMouseClicked(evt);
            }
        });
        artistsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistsTextFieldActionPerformed(evt);
            }
        });

        resetButton.setText("RESET!");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        infoMenuItem.setText("Info");
        infoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(infoMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        CopyMenu.setText("Copy");
        CopyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyMenuActionPerformed(evt);
            }
        });
        jMenu2.add(CopyMenu);

        PasteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.META_MASK));
        PasteMenu.setText("Paste");
        PasteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteMenuActionPerformed(evt);
            }
        });
        jMenu2.add(PasteMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLabel)
                            .addComponent(relDateLabel)
                            .addComponent(popularityLabel)
                            .addComponent(albumIdLabel)
                            .addComponent(albumNameLabel)
                            .addComponent(artistsLabel)
                            .addComponent(linkLabel)
                            .addComponent(jLabel1)
                            .addComponent(coverImageLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(linkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(artistsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(popularityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(albumID, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(albumNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(relDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(UpcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SearchButton)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UpcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(resetButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistsLabel)
                    .addComponent(artistsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumNameLabel)
                    .addComponent(albumNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumIdLabel)
                    .addComponent(albumID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popularityLabel)
                    .addComponent(popularityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relDateLabel)
                    .addComponent(relDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLabel)
                    .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(coverImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpcTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpcTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpcTextFieldActionPerformed

    //Code to copy and paste from the SystemClipboard
    private void PasteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteMenuActionPerformed
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Clipboard clipboard = toolkit.getSystemClipboard();
        String result;
        try {
            result = (String) clipboard.getData(DataFlavor.stringFlavor);
            UpcTextField.setText(result);
        } catch (UnsupportedFlavorException | IOException ex) {
            Logger.getLogger(APIfy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PasteMenuActionPerformed

    private void CopyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyMenuActionPerformed
        Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
        String s = UpcTextField.getSelectedText();
        StringSelection clipString = new StringSelection(s);
        clip.setContents(clipString, null);
    }//GEN-LAST:event_CopyMenuActionPerformed
    
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if (UpcTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Empty UPC field");
            return;
        }
        
        System.out.println("####\nUPC: " + UpcTextField.getText() + "\n####");
        
        //I build the first link to query the API with a link + search query (UPC)
        String link = "https://api.spotify.com/v1/search?q=upc:" + UpcTextField.getText() + "&type=album";
        System.out.println("UPC QUERY LINK:: " + link);
        
        //Instantiating album object
        AlbumUpc album = new AlbumUpc(link);
        
        //calling getJson to get a Json from the GET request. I proceed to printout the response for debugging purposes
        this.jsonObject = album.getJson(link);        
        System.out.println(this.jsonObject.toString());
        
        //checking whethere the upc given corresponds to an actual spotify album
        if(!album.isAlbum()){
            JOptionPane.showMessageDialog(this, "UPC NOT FOUND!");
            return;            
        }
        //I begin extracting json values thanks to the AlbumUpc helper class        
        albumID.setText(album.getAlbumId());
        albumNameTextField.setText(album.getAlbumName());        
               
        //Extracting and showing the album cover thanks to: https://stackoverflow.com/questions/42752611/display-url-image-into-a-jpanel
        Image coverImage = null;
        URL url = null;
        try {
            url = new URL(album.showCoverLink());
        } catch (MalformedURLException ex) {
            Logger.getLogger(APIfy.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            coverImage = ImageIO.read(url);
        } catch (IOException ex) {
            Logger.getLogger(APIfy.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Resizing the cover thanks to: https://stackoverflow.com/questions/6714045/how-to-resize-jlabel-imageicon
        ImageIcon imageIcon = new ImageIcon(coverImage); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(135, 135, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  // transform it back

        coverLabel.setIcon(imageIcon);
        
        //8033772864862
        
        //album web link
        linkTextField.setText("https://play.spotify.com/album/" + albumID.getText());
        
        //Instantiating a new AlbumUpc object passing a new endpoint to get additional info
        link = "https://api.spotify.com/v1/albums/" + albumID.getText();
        AlbumUpc albumApiId = new AlbumUpc(link);
        //calling again getJson to retrieve a different Json
        this.jsonObject = albumApiId.getJson(link);
        //System.out.println("NEW JSON OBJECT: " + this.jsonObject.toString());
        
        
        labelTextField.setText(albumApiId.getLabelApiId());
        relDateTextField.setText(albumApiId.getReleaseDateApiId());
        popularityTextField.setText(albumApiId.getPopularity());
        artistsTextField.setText(albumApiId.getArtistsName());
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void albumIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumIDActionPerformed

    private void albumNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumNameTextFieldActionPerformed

    private void popularityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popularityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popularityTextFieldActionPerformed

    private void relDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relDateTextFieldActionPerformed

    private void labelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTextFieldActionPerformed

    private void linkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkTextFieldActionPerformed

    private void artistsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistsTextFieldActionPerformed

    private void albumIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_albumIDFocusGained
        //8033772864862
        
    }//GEN-LAST:event_albumIDFocusGained

    private void albumIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumIDMouseClicked
       
        clip.copy(albumID.getText());
       
    }//GEN-LAST:event_albumIDMouseClicked

    private void linkTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkTextFieldMouseClicked
       
        clip.copy(linkTextField.getText());
       
    }//GEN-LAST:event_linkTextFieldMouseClicked

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        
      UpcTextField.setText("");
      popularityTextField.setText("");
      linkTextField.setText("");
      relDateTextField.setText("");
      artistsTextField.setText("");
      albumID.setText("");
      albumNameTextField.setText("");
      coverLabel.setIcon(null);
      labelTextField.setText("");
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void infoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Version 1.0\nAlberto Vecchi");
       
    }//GEN-LAST:event_infoMenuItemActionPerformed

    private void popularityTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popularityTextFieldMouseClicked
        
        clip.copy(popularityTextField.getText());
    }//GEN-LAST:event_popularityTextFieldMouseClicked

    private void albumNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumNameTextFieldMouseClicked
        
        clip.copy(albumNameTextField.getText());
    }//GEN-LAST:event_albumNameTextFieldMouseClicked

    private void artistsTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artistsTextFieldMouseClicked
       
        clip.copy(artistsTextField.getText());
    }//GEN-LAST:event_artistsTextFieldMouseClicked

    private void relDateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relDateTextFieldMouseClicked
        
        clip.copy(relDateTextField.getText());
    }//GEN-LAST:event_relDateTextFieldMouseClicked

    private void labelTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTextFieldMouseClicked
        
        clip.copy(labelTextField.getText());
    }//GEN-LAST:event_labelTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APIfy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APIfy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APIfy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APIfy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APIfy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CopyMenu;
    private javax.swing.JMenuItem PasteMenu;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField UpcTextField;
    private javax.swing.JTextField albumID;
    private javax.swing.JLabel albumIdLabel;
    private javax.swing.JLabel albumNameLabel;
    private javax.swing.JTextField albumNameTextField;
    private javax.swing.JLabel artistsLabel;
    private javax.swing.JTextField artistsTextField;
    private javax.swing.JLabel coverImageLabel;
    private javax.swing.JLabel coverLabel;
    private javax.swing.JMenuItem infoMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelLabel;
    private javax.swing.JTextField labelTextField;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JTextField linkTextField;
    private javax.swing.JLabel popularityLabel;
    private javax.swing.JTextField popularityTextField;
    private javax.swing.JLabel relDateLabel;
    private javax.swing.JTextField relDateTextField;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}